
name: cityscapes_paired_with_D_better_params
bs: 8
num_workers: 6
validate: True
dataset:
    name: cityscapes

train:
    lr: 0.0002
    beta1: 0.5
    verbose_period: 100
    epochs: 100

loss:
    lambda_idt: 10
    lambda_C: 5
    lambda_D: 1
