
name: cityscapes_unpaired_better_params
bs: 8
num_workers: 6
validate: True
dataset:
    name: cityscapes
model:
    bilinear_upsample: True
    
train:
    lr: 0.0002
    beta1: 0.5
    verbose_period: 100
    epochs: 50

loss:
    lambda_idt: 0
    lambda_C: 5
    lambda_D: 1
