
name: edges2shoes_unpaired
bs: 8
num_workers: 4
validate: True
dataset:
    name: edges2shoes

train:
    lr: 0.0002
    beta1: 0.5
    verbose_period: 100
    epochs: 12

loss:
    lambda_idt: 0
    lambda_C: 0.5
    lambda_D: 0.5
