
name: edges2shoes_paired_with_D
bs: 16
num_workers: 6
validate: True
dataset:
    name: edges2shoes
model:
    bilinear_upsample: True

train:
    lr: 0.0002
    beta1: 0.5
    verbose_period: 100
    epochs: 12

loss:
    lambda_idt: 0.5
    lambda_C: 0.5
    lambda_D: 0.5
