name: imdb2simpson_idt
bs: 16
num_workers: 6
validate: True
dataset:
    name: folder2folder
    folder_left: 
        root: data/imdb_crop
        filter_folder: true
        crop_scale: 0.55 #0.75
    folder_right:
        root: data/simpsons_cropped
        filter_folder: false
        crop_scale: 0.95 #0.75
model:
    bilinear_upsample: True

train:
    lr: 0.0002
    beta1: 0.5
    verbose_period: 100
    epochs: 150

loss:
    lambda_idt: 1
    lambda_C: 10
    lambda_D: 1
